# Generated by Django 5.2.17 on 2026-09-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('cover_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(blank=True, choices=[('Mint', 'Mint'), ('Near_Mint', 'Near-Mint'), ('Good', 'Good'), ('Poor', 'Poor')], max_length=20)),
            ],
        ),
    ]
