# Generated by Django 5.2.17 on 2026-09-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_added',
        ),
    ]
