# Generated by Django 5.2.17 on 2026-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0002_remove_book_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('format', models.CharField(blank=True, choices=[('DVD', 'DVD'), ('Blu-ray', 'Blu-ray'), ('HD-DVD', 'HD-DVD'), ('VHS', 'VHS'), ('LaserDisc', 'LaserDisc'), ('Betamax', 'Betamax')], max_length=20)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('series_num', models.FloatField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, choices=[('Factory Sealed', 'Factory Sealed'), ('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Great', 'Great'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('format', models.CharField(blank=True, choices=[('DVD', 'DVD'), ('Blu-ray', 'Blu-ray'), ('HD-DVD', 'HD-DVD'), ('VHS', 'VHS'), ('LaserDisc', 'LaserDisc'), ('Betamax', 'Betamax')], max_length=20)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('series_num', models.FloatField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, choices=[('Factory Sealed', 'Factory Sealed'), ('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Great', 'Great'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('developer', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('Nintendo Switch 2', 'Nintendo Switch 2'), ('Playstation 5', 'PlayStation 5'), ('Xbox Series', 'Xbox Series X|S'), ('Nintendo Switch', 'Nintendo Switch'), ('Playstation 4', 'PlayStation 4'), ('Xbox One', 'Xbox One'), ('Nintendo Wii U', 'Nintendo Wii U'), ('PS Vita', 'PS Vita'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Playstation 3', 'PlayStation 3'), ('Nintendo Wii', 'Nintendo Wii'), ('Xbox 360', 'Xbox 360'), ('PSP', 'PSP'), ('Nintendo DS', 'Nintendo DS'), ('Xbox', 'Xbox'), ('Nintendo Gamecube', 'Nintendo Gamecube'), ('Game Boy Advance', 'Game Boy Advance'), ('Playstation 2', 'PlayStation 2'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Game Boy Color', 'Game Boy Color'), ('Nintendo 64', 'Nintendo 64'), ('Playstation', 'PlayStation'), ('Super Nintendo', 'Super Nintendo'), ('Game Boy', 'Game Boy'), ('Sega Genesis', 'Sega Genesis'), ('NES', 'NES'), ('PC', 'PC'), ('Other', 'Other')], max_length=50)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('series_num', models.FloatField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, choices=[('Factory Sealed', 'Factory Sealed'), ('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Great', 'Great'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='series_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('Factory Sealed', 'Factory Sealed'), ('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Great', 'Great'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20),
        ),
    ]
