# Generated by Django 5.2.17 on 2026-10-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0003_movie_tv_videogame_book_release_date_book_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv',
            name='series',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='series_num',
        ),
        migrations.AddField(
            model_name='tv',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
