# Generated by Django 5.2.17 on 2026-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0004_remove_tv_series_remove_tv_series_num_tv_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='release_date',
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogame',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
